Revert -Wcast-qual const drop warnings silencing
This breaks the build for a reason I cannot figure out (and don't have
the time to do so). Revert for now.

target asm: libpng <= external/libpng/arm/filter_neon.S
external/libpng/arm/../pngpriv.h:476:24: error: unexpected token in argument list
      typedef unsigned long png_ptruint;
                       ^

Revert "tweak"
This reverts commit 4828af647919241917fb60f98db07c8d861e784e.

Revert "silence clang -Wcast-qual const drop warnings"
This reverts commit d71043bc8baff91fad1ee73dec6af95014e529a4.